---
- name: Security hardening for homelab servers
  hosts: all
  become: true
  gather_facts: true

  vars:
    # SSH configuration
    ssh_port: "{{ custom_ssh_port | default(22) }}"
    ssh_permit_root_login: "{{ ssh_root_login | default('no') }}"
    ssh_password_auth: "{{ ssh_password_authentication | default('no') }}"
    ssh_max_auth_tries: "{{ ssh_max_tries | default(3) }}"

    # Firewall configuration
    firewall_allowed_ports:
      - "{{ ssh_port }}/tcp"
      - "80/tcp"
      - "443/tcp"

    # Fail2ban configuration
    fail2ban_services:
      - ssh
      - apache-auth
      - nginx-http-auth

  tasks:
    - name: Update system packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe
      tags: update

    - name: Install security packages
      ansible.builtin.apt:
        name:
          - fail2ban
          - ufw
          - unattended-upgrades
          - apt-listchanges
          - logwatch
          - rkhunter
          - chkrootkit
        state: present
      tags: packages

    - name: Configure SSH daemon
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: true
      loop:
        - { regexp: "^#?Port", line: "Port {{ ssh_port }}" }
        - {
            regexp: "^#?PermitRootLogin",
            line: "PermitRootLogin {{ ssh_permit_root_login }}",
          }
        - {
            regexp: "^#?PasswordAuthentication",
            line: "PasswordAuthentication {{ ssh_password_auth }}",
          }
        - {
            regexp: "^#?MaxAuthTries",
            line: "MaxAuthTries {{ ssh_max_auth_tries }}",
          }
        - { regexp: "^#?X11Forwarding", line: "X11Forwarding no" }
        - { regexp: "^#?ClientAliveInterval", line: "ClientAliveInterval 300" }
        - { regexp: "^#?ClientAliveCountMax", line: "ClientAliveCountMax 2" }
      notify: restart ssh
      tags: ssh

    - name: Configure UFW firewall
      community.general.ufw:
        rule: allow
        port: "{{ item.split('/')[0] }}"
        proto: "{{ item.split('/')[1] }}"
      loop: "{{ firewall_allowed_ports }}"
      tags: firewall

    - name: Enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming
      tags: firewall

    - name: Configure fail2ban
      ansible.builtin.template:
        src: jail.local.j2
        dest: /etc/fail2ban/jail.local
        backup: true
      notify: restart fail2ban
      tags: fail2ban

    - name: Enable and start fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        enabled: true
        state: started
      tags: fail2ban

    - name: Configure automatic security updates
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - {
            regexp: '//.*"${distro_id}:${distro_codename}-security"',
            line: '        "${distro_id}:${distro_codename}-security";',
          }
        - {
            regexp: "//Unattended-Upgrade::AutoFixInterruptedDpkg",
            line: 'Unattended-Upgrade::AutoFixInterruptedDpkg "true";',
          }
        - {
            regexp: "//Unattended-Upgrade::Remove-Unused-Dependencies",
            line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";',
          }
      tags: auto-updates

    - name: Set kernel parameters for security
      ansible.posix.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: true
      loop:
        - { name: "net.ipv4.conf.default.rp_filter", value: "1" }
        - { name: "net.ipv4.conf.all.rp_filter", value: "1" }
        - { name: "net.ipv4.icmp_echo_ignore_broadcasts", value: "1" }
        - { name: "net.ipv4.conf.all.accept_redirects", value: "0" }
        - { name: "net.ipv6.conf.all.accept_redirects", value: "0" }
        - { name: "net.ipv4.conf.all.send_redirects", value: "0" }
        - { name: "net.ipv4.conf.all.accept_source_route", value: "0" }
        - { name: "net.ipv6.conf.all.accept_source_route", value: "0" }
      tags: kernel

  handlers:
    - name: restart ssh
      ansible.builtin.systemd:
        name: ssh
        state: restarted

    - name: restart fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        state: restarted
